export type EngagementStatus = 'Validé' | 'En cours' | 'En retard' | 'Annulé' | 'Planifié'
export type EngagementCategory = 'Infrastructure' | 'Éducation' | 'Santé' | 'Agriculture' | 'Transport' | 'Énergie'

export interface Engagement {
  id: string
  reference: string
  objet: string
  beneficiaire: string
  montant: number
  statut: EngagementStatus
  categorie: EngagementCategory
  echeance: string
  tauxRealisation: number
  dateCreation: string
}

export const engagements: Engagement[] = [
  {
    id: '1',
    reference: 'ENG-2026-001',
    objet: 'Construction_route_nationale_RN7',
    beneficiaire: 'Société Nationale des Travaux Publics',
    montant: 450000000,
    statut: 'En cours',
    categorie: 'Infrastructure',
    echeance: '2026-12-31',
    tauxRealisation: 45,
    dateCreation: '2026-01-15',
  },
  {
    id: '2',
    reference: 'ENG-2026-002',
    objet: 'Réhabilitation_lycée_Marien_Ngouabi',
    beneficiaire: 'Ministère de l\'Éducation Nationale',
    montant: 125000000,
    statut: 'Validé',
    categorie: 'Éducation',
    echeance: '2026-09-30',
    tauxRealisation: 100,
    dateCreation: '2026-01-20',
  },
  {
    id: '3',
    reference: 'ENG-2026-003',
    objet: 'Équipement_hôpital_central_de_Brazzaville',
    beneficiaire: 'CHU de Brazzaville',
    montant: 280000000,
    statut: 'En retard',
    categorie: 'Santé',
    echeance: '2026-06-30',
    tauxRealisation: 30,
    dateCreation: '2026-02-01',
  },
  {
    id: '4',
    reference: 'ENG-2026-004',
    objet: 'Programme_appui_agricole_Pool',
    beneficiaire: 'Union des Coopératives Agricoles',
    montant: 85000000,
    statut: 'Validé',
    categorie: 'Agriculture',
    echeance: '2026-10-15',
    tauxRealisation: 100,
    dateCreation: '2026-02-10',
  },
  {
    id: '5',
    reference: 'ENG-2026-005',
    objet: 'Modernisation_réseau_ferroviaire_CFCO',
    beneficiaire: 'CFCO - Chemin de Fer Congo-Océan',
    montant: 620000000,
    statut: 'Planifié',
    categorie: 'Transport',
    echeance: '2027-06-30',
    tauxRealisation: 5,
    dateCreation: '2026-02-15',
  },
  {
    id: '6',
    reference: 'ENG-2026-006',
    objet: 'Centrale_solaire_du_Niari',
    beneficiaire: 'SNE - Société Nationale d\'Électricité',
    montant: 350000000,
    statut: 'En cours',
    categorie: 'Énergie',
    echeance: '2027-03-31',
    tauxRealisation: 55,
    dateCreation: '2026-03-01',
  },
  {
    id: '7',
    reference: 'ENG-2026-007',
    objet: 'Construction_pont_sur_le_fleuve_Congo',
    beneficiaire: 'Entreprise Générale de Construction',
    montant: 890000000,
    statut: 'En cours',
    categorie: 'Infrastructure',
    echeance: '2028-12-31',
    tauxRealisation: 20,
    dateCreation: '2026-03-05',
  },
  {
    id: '8',
    reference: 'ENG-2026-008',
    objet: 'Fourniture_manuels_scolaires_primaire',
    beneficiaire: 'Éditions Nathan Afrique',
    montant: 42000000,
    statut: 'Validé',
    categorie: 'Éducation',
    echeance: '2026-08-31',
    tauxRealisation: 100,
    dateCreation: '2026-03-10',
  },
  {
    id: '9',
    reference: 'ENG-2026-009',
    objet: 'Campagne_vaccination_rougeole',
    beneficiaire: 'OMS Congo - Bureau National',
    montant: 67000000,
    statut: 'Annulé',
    categorie: 'Santé',
    echeance: '2026-07-31',
    tauxRealisation: 0,
    dateCreation: '2026-03-15',
  },
  {
    id: '10',
    reference: 'ENG-2026-010',
    objet: 'Irrigation_périmètre_Sangha',
    beneficiaire: 'Projet de Développement Rural Intégré',
    montant: 150000000,
    statut: 'En retard',
    categorie: 'Agriculture',
    echeance: '2026-05-31',
    tauxRealisation: 40,
    dateCreation: '2026-04-01',
  },
  {
    id: '11',
    reference: 'ENG-2026-011',
    objet: 'Agrandissement_aéroport_Maya_Maya',
    beneficiaire: 'Aéroports du Congo',
    montant: 520000000,
    statut: 'Planifié',
    categorie: 'Transport',
    echeance: '2028-06-30',
    tauxRealisation: 0,
    dateCreation: '2026-04-10',
  },
  {
    id: '12',
    reference: 'ENG-2026-012',
    objet: 'Ligne_électrique_Pointe_Noire_Dolisie',
    beneficiaire: 'SNE - Société Nationale d\'Électricité',
    montant: 210000000,
    statut: 'En cours',
    categorie: 'Énergie',
    echeance: '2027-01-31',
    tauxRealisation: 65,
    dateCreation: '2026-04-15',
  },
  {
    id: '13',
    reference: 'ENG-2026-013',
    objet: 'Réfection_bâtiments_administratifs',
    beneficiaire: 'Ministère des Travaux Publics',
    montant: 95000000,
    statut: 'Validé',
    categorie: 'Infrastructure',
    echeance: '2026-11-30',
    tauxRealisation: 100,
    dateCreation: '2026-05-01',
  },
  {
    id: '14',
    reference: 'ENG-2026-014',
    objet: 'Formation_enseignants_secondaire',
    beneficiaire: 'ENS - École Normale Supérieure',
    montant: 35000000,
    statut: 'En cours',
    categorie: 'Éducation',
    echeance: '2026-12-31',
    tauxRealisation: 50,
    dateCreation: '2026-05-10',
  },
  {
    id: '15',
    reference: 'ENG-2026-015',
    objet: 'Centre_santé_maternelle_Owando',
    beneficiaire: 'Croix-Rouge Congolaise',
    montant: 78000000,
    statut: 'Validé',
    categorie: 'Santé',
    echeance: '2026-10-31',
    tauxRealisation: 100,
    dateCreation: '2026-05-15',
  },
  {
    id: '16',
    reference: 'ENG-2026-016',
    objet: 'Projet_cacao_bassin_Kouilou',
    beneficiaire: 'Coopérative des Producteurs de Cacao',
    montant: 110000000,
    statut: 'En retard',
    categorie: 'Agriculture',
    echeance: '2026-04-30',
    tauxRealisation: 25,
    dateCreation: '2026-01-05',
  },
  {
    id: '17',
    reference: 'ENG-2026-017',
    objet: 'Route_departementale_Lékoumou',
    beneficiaire: 'Société d\'Entreprises de BTP',
    montant: 180000000,
    statut: 'En cours',
    categorie: 'Transport',
    echeance: '2027-06-30',
    tauxRealisation: 35,
    dateCreation: '2026-06-01',
  },
  {
    id: '18',
    reference: 'ENG-2026-018',
    objet: 'Barrage_hydroélectrique_Liouesso',
    beneficiaire: 'SNE - Société Nationale d\'Électricité',
    montant: 1200000000,
    statut: 'Planifié',
    categorie: 'Énergie',
    echeance: '2029-12-31',
    tauxRealisation: 2,
    dateCreation: '2026-06-10',
  },
  {
    id: '19',
    reference: 'ENG-2026-019',
    objet: 'Drainage_urbain_Plateaux_Bacongo',
    beneficiaire: 'Mairie de Brazzaville',
    montant: 62000000,
    statut: 'Annulé',
    categorie: 'Infrastructure',
    echeance: '2026-08-31',
    tauxRealisation: 10,
    dateCreation: '2026-06-15',
  },
  {
    id: '20',
    reference: 'ENG-2026-020',
    objet: 'Université_numérique_du_Congo',
    beneficiaire: 'Université Marien Ngouabi',
    montant: 175000000,
    statut: 'En cours',
    categorie: 'Éducation',
    echeance: '2027-09-30',
    tauxRealisation: 60,
    dateCreation: '2026-07-01',
  },
  {
    id: '21',
    reference: 'ENG-2026-021',
    objet: 'Laboratoire_analyses_médicales_Pointe_Noire',
    beneficiaire: 'Centre Hospitalier de Pointe-Noire',
    montant: 92000000,
    statut: 'Validé',
    categorie: 'Santé',
    echeance: '2026-12-15',
    tauxRealisation: 100,
    dateCreation: '2026-07-10',
  },
  {
    id: '22',
    reference: 'ENG-2026-022',
    objet: 'Transformation_manioc_Niari',
    beneficiaire: 'Groupement des Femmes Agricultrices',
    montant: 45000000,
    statut: 'En cours',
    categorie: 'Agriculture',
    echeance: '2027-03-31',
    tauxRealisation: 70,
    dateCreation: '2026-07-15',
  },
  {
    id: '23',
    reference: 'ENG-2026-023',
    objet: 'Gare_routière_Ollombo',
    beneficiaire: 'Conseil Départemental des Plateaux',
    montant: 130000000,
    statut: 'En retard',
    categorie: 'Transport',
    echeance: '2026-08-31',
    tauxRealisation: 15,
    dateCreation: '2026-02-20',
  },
  {
    id: '24',
    reference: 'ENG-2026-024',
    objet: 'Éclairage_public_ville_de_Nkayi',
    beneficiaire: 'Mairie de Nkayi',
    montant: 55000000,
    statut: 'Validé',
    categorie: 'Énergie',
    echeance: '2026-11-30',
    tauxRealisation: 100,
    dateCreation: '2026-08-01',
  },
  {
    id: '25',
    reference: 'ENG-2026-025',
    objet: 'Marché_couvert_Mossendjo',
    beneficiaire: 'Chambre de Commerce et d\'Industrie',
    montant: 70000000,
    statut: 'Planifié',
    categorie: 'Infrastructure',
    echeance: '2027-06-30',
    tauxRealisation: 0,
    dateCreation: '2026-08-10',
  },
]

export const categories: EngagementCategory[] = [
  'Infrastructure',
  'Éducation',
  'Santé',
  'Agriculture',
  'Transport',
  'Énergie',
]

export const statuses: EngagementStatus[] = [
  'Validé',
  'En cours',
  'En retard',
  'Annulé',
  'Planifié',
]

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('fr-FR', {
    style: 'currency',
    currency: 'XAF',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

export function formatNumber(num: number): string {
  return new Intl.NumberFormat('fr-FR').format(num)
}
